apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLbXhSN3hLRTVkNUxJbC9xY28rCkVZNzd1cmYxUE5QbDlLY0owL0RRRis3U1lkdU54a2ZFUTlXQk5sblJaRkZpczFBMDQzWHNKRTBUWHlNZjNNcDEKWDVYdXhiYmhiMVhPcERoYTliZ3E0L1RFcTBSVm5jYWtYTGd5Q2tlYkRyZ1dpNExtWXFWYXE5TEtmODdQbHRVSAp5dVRKQ0RmMVkrL2YvQ3Y0cU02ZklIN3hibHpCdVZYUXJyR2hlN3RKcWpqdXMrWnMzemRnQ3ZGdkdldjl2R0ZWCndDRE5uUGxDbzNodXJCTHFza2xGV2NSdi9SZzcvampQRWRONCs0VnUwTEp0OFBIK2xLMFZOS0Jlc1BsRk55VTEKRFM4cHN5eFVvYS9TYWIzbW1JUmxxWHJFUlpOOHFiQXc5VnFGK3VDWFA1dTJLanJ0VkhpSEwrdTgvTTFrVzNaKwpyZ1VDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUEwa2ltSVRIei9sb0VCNGhSVnduaTJ3L09iClVNNkkyOWZYNnA0MnYrOGZIQ2RtZHNYNDMxRTlReWFyZzFFOHFKTU5zQjJBK0F6OU0vdmVBREhXaEhhcDRPclkKZnBkTkV5dFpqeEJpdVNNblkzYUttekx2UFc3TCsrdWx6OUNBakRKSXlEUXh2UmJqeHdEZk1xc2NnR25pZlZPMAp3OG9GZHpEclptci9QczZINmZIYlVxRFExSXNIRm9DczhFa21QWUpPd1BIM3YybEZTbDZvWkhlTXIvVzI2Y1pXCkYwNGRYbFNXdFZDQ3BrVWh0WHNnUzQwS1pQeWpLZlJqZHZJcnBvU2tHUXdqT1Z1bFpNMmRFVUJjNDhuMTQrby8KaUJPMmpmZ1dWb0dqSVNLT1VjL3BmNmMrU3NNa3BRTUcreGtKN3c2a2xCTklYR0xkK1hsVHd6VWRlcWp2Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - client auth
